django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('ESL/', include('ESL.url')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/ESL/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Snippet(models.Model):
    name = models.CharField(max_length=100)
    body = models.TextField()
    def _str_(self):
        return self.name



class ExamQ(models.Model):
    UserI = models.ForeignKey(User,blank=True,on_delete=models.CASCADE)
    marks = models.IntegerField()
    q1 = models.CharField(max_length=100)
    q2 = models.CharField(max_length=100)
    q3 = models.CharField(max_length=100)
    q4 = models.CharField(max_length=100)

class ExamV(models.Model):
    UserI = models.ForeignKey(User,blank=True,on_delete=models.CASCADE)
    marks = models.IntegerField()
    q1 = models.CharField(max_length=100)
    q2 = models.CharField(max_length=100)
    q3 = models.CharField(max_length=100)
    q4 = models.CharField(max_length=100)

class TMarks(models.Model):
    UserI = models.ForeignKey(User,blank=True,on_delete=models.CASCADE)
    tmarks = models.IntegerField()

class Dmarks(models.Model):
    UserI = models.ForeignKey(User,blank=True,on_delete=models.CASCADE)
    dmarks = models.IntegerField()
    date_now  = models.CharField(max_length=100,default='NULL')

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    

django_project/ESL/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,Submit
from django import forms
from .models import Snippet,ExamQ,ExamV,Profile
from django.core.validators import RegexValidator
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User





class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')

class ExamQt(forms.ModelForm):
    class Meta():
        model = ExamQ
        fields =('q1','q2','q3','q4')

class ExamVt(forms.ModelForm):
    class Meta():
        model = ExamV
        fields =('q1','q2','q3','q4')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']




#---------------------- not realy usefull =-----------------------------------
class NameWidget(forms.MultiWidget):

    def __init__(self, attrs=None):
        super().__init__([
            forms.TextInput(),
            forms.TextInput()
        ],attrs)

    def decompress(self,value):
        if value:
            return value.split(' ')
        return ['', '']
#---------------------- not realy usefull =-----------------------------------
class NameField(forms.MultiValueField):

    widget = NameWidget

    def __init__(self,*args,**kwargs):

        fields = (
            forms.CharField(validators=[
                RegexValidator(r'[a-zA-Z]+','enter a valid name ()')
            ]),
            forms.CharField(validators=[
                RegexValidator(r'[a-zA-Z]+','enter a valid name ()')
            ])
        )

        super().__init__(fields,*args,**kwargs)
    def compress(self,data_list):
        return f'{data_list[0]} {data_list[1]}'
#--------------------------For practice ------------------------------------
class ContactForm(forms.Form):
    name = NameField()
    email = forms.EmailField(label='E-Mail')
    #category = forms.ChoiceField(choices[('question','Question'),('other','Other')])
    subject = forms.CharField(required=False)
    body = forms.CharField(widget=forms.Textarea)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'POST'

        self.helper.layout = Layout(
            'name',
            'email',
            'subject',
            'body',
            Submit('submit','Submit',css_class='btn-success')
        )
#--------------------------For practice ------------------------------------
class SnippetForm(forms.ModelForm):

    class Meta:
        model = Snippet
        fields = ('name','body')


#---------------------not in use in Views-----------------------------
class SignUpForm(UserCreationForm): 
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ( 'first_name', 'last_name', 'email', 'password' )
    def __init__ (self, *args, **kwargs):
        super(SignUpForm,self).__init__(*args, **kwargs)
        #remove what you like...
        self.fields.pop ('password1')
        self.fields.pop ('password2')

#---------------------not in use in Views-----------------------------
class CustomUserCreationForm(forms.Form): 
    first_name = forms.CharField( min_length=4, max_length=150)
    last_name = forms.CharField( min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password = forms.CharField(label='Enter password', widget=forms.PasswordInput)


    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email


    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['first_name'],
            self.cleaned_data['last_name'],
            self.cleaned_data['email'],
            self.cleaned_data['password']
        )
        return user

django_project/ESL/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,HttpResponseRedirect
from .models import ExamQ,ExamV,TMarks,Dmarks,Profile
from .forms import ContactForm,SnippetForm,UserUpdateForm,ProfileUpdateForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm,CustomUserCreationForm,UserForm,ExamQt,ExamVt
from django.contrib import auth
from datetime import datetime
from django.contrib import messages
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your views here.

def login(request):#login
    return render(request,'ESL/login.html')

def home(request):#home page or first page in app
    return render(request,'ESL/home.html')

def learning(request):#learning page in webapp
    return render(request,'ESL/learning.html')

def Contact_Us(request):#contact page in webapp
    return render(request,'ESL/Contact_Us.html')

def home2(request):#home page After Sign-in of User redirect
    return render(request,'ESL/home2.html')

def exam(request):#videos Page
    return render(request,'ESL/video.html')

def exam_genre(request):#videos/genre Page
    return render(request,'ESL/video_genre.html')

def exam_genre_exam(request):#videos/genre/exam Page
    return render(request,'ESL/video_genre_exam.html')

def audio(request):#audio Page
    return render(request,'ESL/audio.html')

def audio_genre(request):#audio/genre Page
    return render(request,'ESL/audio_genre.html')

def audio_genre_exam(request):#audio/genre/exam Page
    return render(request,'ESL/audio_genre_exam.html')

def about(request):#about page
    return render(request,'ESL/about.html')

def prac(request):#practice page
    profile = Profile.objects.get(user=request.user)
    TMark = TMarks.objects.get(UserI=request.user)
    Dmark = Dmarks.objects.filter(UserI=request.user).order_by('-id')[:7]
    return render(request, 'ESL/prac.html', {'TMarks': TMark, 'Dmarks': Dmark , 'Profile':profile})




def Ques(request):#Function Based View that Checks correct ans and saves it
    if request.method == 'POST':#if any thing enters
        form = ExamQt(request.POST)
        print("user")
        print(request.user.id)
        user = User.objects.get(username=request.user)#gets Active User instance
        print(user)
        if form.is_valid():
            n=0
            now = datetime.now()
            print(now.strftime("%Y-%m-%d %H:%M:%S"))
            qq=form.cleaned_data['q1']
            if qq == "dash": #if Ans is correct adds score
                n=1

            qq=form.cleaned_data['q2']
            if qq == "shock":
                n=n+1
            qq=form.cleaned_data['q3']
            if qq == "dash":
                n=n+1
            qq=form.cleaned_data['q4']
            if qq == "nail":
                n=n+1

            
            if TMarks.objects.filter(UserI=request.user).exists():
                TMark = TMarks.objects.get(UserI=request.user)
                TMark.tmarks = TMark.tmarks + n
                TMark.save()
            else:
                TMark = TMarks(UserI=request.user)
                TMark.tmarks = n
                TMark.save()

            if Dmarks.objects.filter(UserI=request.user,date_now=now.strftime("%Y-%m-%d")).exists():
                Dmark = Dmarks.objects.filter(UserI=request.user)[0]
                Dmark.dmarks = Dmark.dmarks + n
                Dmark.save()
            else:
                Dmark = Dmarks(UserI=request.user,date_now=now.strftime("%Y-%m-%d"))
                Dmark.dmarks = n
                Dmark.save()

            q=ExamQ(UserI=request.user)

            q.marks = n
            print("hi")
            #enters data into the q model
            q.User1=request.user
            q.q1=form.cleaned_data['q1']
            q.q2=form.cleaned_data['q2']
            q.q3=form.cleaned_data['q3']
            q.q4=form.cleaned_data['q4']
            q.save()
            form = ExamQt()
            print("success")
            query=q

            return render(request,'ESL/result.html',{'query':query})#Renders user marks html



    form = ExamQt()
    return render(request,'ESL/video_genre_exam.html',{'form':form})#Renders user Questions html

def QuesA(request):#Function Based View that Checks correct ans and saves it
    if request.method == 'POST':#if any thing enters
        form = ExamVt(request.POST)
        print("user")
        print(request.user.id)
        user = User.objects.get(username=request.user)#gets Active User instance
        print(user)
        if form.is_valid():
            n=0
            now = datetime.now()
            qq=form.cleaned_data['q1']
            if qq == "dash": #if Ans is correct adds score
                n=1

            qq=form.cleaned_data['q2']
            if qq == "shock":
                n=n+1
            qq=form.cleaned_data['q3']
            if qq == "dash":
                n=n+1
            qq=form.cleaned_data['q4']
            if qq == "nail":
                n=n+1

            if TMarks.objects.filter(UserI=request.user).exists():
                TMark = TMarks.objects.get(UserI=request.user)
                TMark.tmarks = TMark.tmarks + n
                TMark.save()
            else:
                TMark = TMarks(UserI=request.user)
                TMark.tmarks = n
                TMark.save()

            if Dmarks.objects.filter(UserI=request.user,date_now=now.strftime("%Y-%m-%d")).exists():
                Dmark = Dmarks.objects.filter(UserI=request.user)[0]
                Dmark.dmarks = Dmark.dmarks + n
                Dmark.save()
            else:
                Dmark = Dmarks(UserI=request.user,date_now=now.strftime("%Y-%m-%d"))
                Dmark.dmarks = n
                Dmark.save()
        
            q=ExamV(UserI=request.user)

            q.marks = n
            print("hi")
            #enters data into the q model
            q.User1=request.user
            q.q1=form.cleaned_data['q1']
            q.q2=form.cleaned_data['q2']
            q.q3=form.cleaned_data['q3']
            q.q4=form.cleaned_data['q4']
            q.save()
            form = ExamVt()
            print("success")
            query=q

            return render(request,'ESL/result.html',{'query':query})#Renders user marks html



    form = ExamVt()
    return render(request,'ESL/audio_genre_exam.html',{'form':form})#Renders user Questions html

def editprofile(request):#edit profile page
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid(): #
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('ESL-practice')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm()

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'ESL/editprofile.html', context)

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

def loginpage(request):#login page
    if request.method == 'POST':
        username = request.POST['username']
        print(username)
        password =  request.POST['password']
        print(password)
        user = auth.authenticate(username=username, password=password)#checks users auth
        print(user)
        if user is not None and user.is_active:
            # Correct password, and the user is marked "active"
            auth.login(request, user)
            # Redirect to a success page.
            return redirect('ESL-home2')
        else:
            return render(request, 'ESL/signin.html', {})
    return render(request, 'ESL/signin.html', {})


def profile(request):#profile page
    if request.user:
        query = request.user
        print('profile ki redirect ayinapudu')
        print(request.user)
        query = User.objects.filter(email=request.user.email)#filter current user instance

        return render(request, 'ESL/profile.html', {"query":query})
    else:
        return render(request, 'ESL/login.html', {})

        
def logot(request):#logot view
    auth.logout(request)#logout chestadhi
    return redirect("ESL-home")

def signup(request):#Function Based Signin View for first time user login
    if request.method == 'POST':
        form =  UserForm(request.POST)
        form.errors
        print(form.errors)

        if form.is_valid():
            user = User()
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            user.set_password(form.cleaned_data['password'])
            user.save()
            print(user)
            return redirect('ESL-home2')
    else:
        form =  UserForm()
    return render(request, 'ESL/signin.html', {'form': form})











def contact(request):#for practice nothing special
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['name']
            email = form.cleaned_data['email']

            print(name)

    form = ContactForm()
    return render(request,'ESL/form.html',{'form':form})


def snippet_detail(request):#for practice nothing special
    if request.method == 'POST':
        form = SnippetForm(request.POST)

        if form.is_valid():

django_project/ESL/templates/ESL/about.html
{% extends "ESL/base.html" %}
{% block content %}
<h2>about page <small>fuck</small></h2>



{% endblock content%}

django_project/ESL/templates/ESL/audio_genre.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>audio</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'ESL\css\audio.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar">
        <div class="container"><a class="navbar-brand logo" href="#">LINGISTOR</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse"
                id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="index.html">Home!</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="features.html">Features</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="pricing.html">Pricing</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="about-us.html">About Us</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="contact-us.html">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <h1 id="Animation_h">Audio/Bristish</h1>
    <div id="Acontainer"><a href="{% url 'ESL-audio-genre-exam' %}"> 
<div class="grid-item">
    <img src="{% static 'ESL\images\A1.jpg' %}" style="width:24vw;height: 24vh">
    <div class="overlay" >
    Conversation1
    </div>
</div>
</a><a href="{% url 'ESL-audio-genre-exam' %}"> 
<div class="grid-item">
    <img src="{% static 'ESL\images\A2.jpg' %}" style="width:24vw;height: 24vh">
    <div class="overlay" >
    Conversation2
    </div>
</div>
</a><a href="{% url 'ESL-audio-genre-exam' %}"> 
<div class="grid-item">
    <img src="{% static 'ESL\images\A3.png' %}" style="width:24vw;height: 24vh">
    <div class="overlay" >
    Conversation3
    </div>
</div>
</a></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script src="https://www.youtube.com/iframe_api"></script>
    <script src="{% static 'ESL\js\audio.min.js' %}"></script>
</body>

</html>

django_project/ESL/templates/ESL/exam.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Untitled</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'ESL\css\style_exam.min.css' %}">
</head>

<body class="text-center" id="color">
    <div id="backgroud-image" class="div-maincolor">
        <div>
            <!-- Start: logo_re -->
            <div class="text-left" id="top-logo" style="height: 74px;margin: 0;padding: 1;">
                <h1 id="hedi" style="font-family: Aleo, serif;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Lingistor</h1><img id="top_logo" src="{% static 'ESL\images\logo_O1.png' %}" alt="Smiley face" height="50" width="80">
</div>
            <!-- End: logo_re -->
        </div>
        <!-- Start: top_nav_re -->  <nav class="d-flex navbar navbar-expand-sm navbar-custom sticky-top shadow-lg p-3 mb-5">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse d-flex" id="navbarCustom">

  <ul class="navbar-nav">
      <li class="nav-item">
      <a class="nav-link text-center" href="{% url 'ESL-home2' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-center" href="{% url 'ESL-Contact_Us' %}">Contact Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-center" href="{% url 'ESL-learning' %}" style="">Learning</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-center" href="{% url 'ESL-exam' %}">Exam</a>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle text-center" href="{% url 'ESL-practice' %}" id="navbarDropdown" data-toggle="dropdown">
        Practice
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'ESL-practice' %}">Interview Skills</a>
        <a class="dropdown-item" href="#">Writing Skills</a>
        <a class="dropdown-item" href="#">Reading Skills</a>
      </div>
        </li>

      <li class=" ml-auto">
      <a class="nav-link text-center ml-auto" href="{% url 'ESL-exam' %}"></a>
    </li>
      <li class=" ml-auto">
      <a class="nav-link text-center ml-auto" href="{% url 'ESL-exam' %}"></a>
          <li class=" ml-auto">
      <a class="nav-link text-center ml-auto" href="{% url 'ESL-exam' %}"></a>
              <li class=" ml-auto">
      <a class="nav-link text-center ml-auto" href="{% url 'ESL-exam' %}"></a>
    </li><li class=" ml-auto">
      <a class="nav-link text-center ml-auto" href="{% url 'ESL-exam' %}"></a>
    </li>


      <li class="nav-item ml-auto">
      <a class="nav-link text-center ml-auto" href="{% url 'logot' %}">Logout</a>
    </li>
  </ul>
</div>
</nav>
        <!-- End: top_nav_re -->
        <!-- Start: side-nav-bar_re --><ul class="nav flex-column shadow d-flex sidebar mobile-hid">
    <li class="nav-item logo-holder">
        <div class="text-center text-white logo py-4 mx-4"><a class="text-dark text-decoration-none" id="title" href="#"><strong>Sidebar</strong></a><a class="text-white float-right" id="sidebarToggleHolder" href="#"><i class="fas fa-bars" id="sidebarToggle"></i></a></div>
    </li>
    <li class="nav-item"><a class="nav-link active text-left text-dark py-1 px-0" href="#"><i class="fas fa-tachometer-alt mx-3"></i><span class="text-nowrap mx-2">Dashboard</span></a></li>
    <li class="nav-item"><a class="nav-link text-left text-dark py-1 px-0" href="{% url 'profile' %}"><i class="fas fa-user mx-3"></i><span class="text-nowrap mx-2">User profile</span></a></li>

    <li class="nav-item"><a class="nav-link text-left text-dark py-1 px-0" href="#"><i class="fas fa-archive mx-3"></i><span class="text-nowrap mx-2">Archive</span></a></li>
    <li class="nav-item"><a class="nav-link text-left text-dark py-1 px-0" href="#"><i class="fas fa-chart-bar mx-3"></i><span class="text-nowrap mx-2">Statistics</span></a></li>
    <li class="nav-item dropdown"><a data-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link text-left text-dark py-1 px-0 position-relative" href="#"><i class="fas fa-sliders-h mx-3"></i><span class="text-nowrap mx-2">Settings</span><i class="fas fa-caret-down float-none float-lg-right fa-sm"></i></a>
        <div
            role="menu" class="dropdown-menu border-0 animated fadeIn"><a role="presentation" class="dropdown-item text-white" href="#"><span>Change password</span></a><a role="presentation" class="dropdown-item text-white" href="#"><span>Change email</span></a><a role="presentation" class="dropdown-item text-white"
                href="#"><span>More</span></a></div>
    </li>
    <li class="nav-item"><a class="nav-link text-left text-dark py-1 px-0" href="#"><i class="fas fa-sign-out-alt mx-3"></i><i class="fa fa-caret-right d-none position-absolute"></i><span class="text-nowrap mx-2">Log out</span></a></li>
</ul>
        <!-- End: side-nav-bar_re -->
        <div class="align-self-center">
            <h1 class="text-center">Exam</h1>
        </div>
        <h5>Heading</h5>
        <div class="text-center">
            <!-- Start: youtube video --><div class="col">

<iframe width="800" height="480" src="https://www.youtube.com/embed/Rnwwo9Zol6w" frameborder="0" allow=" picture-in-picture"></iframe></div>
            <!-- End: youtube video -->
            <h1 style="padding: 17px;height: 82px;">The questions are below</h1>
        </div>
        <form method="POST" action="{% url 'ESL-exam' %}">
          {% csrf_token %}
        <div class="d-flex flex-column justify-content-center align-items-center" style="height: 509px;">
            <h5 style="padding: 10px;">what is the name of child here</h5>
            <!-- Start: Google Style Text Input --><div class="form-group">

    <input type="text" name="q1" maxlength="100" required id="id_q1">
    <span class="highlight"></span>
    <span class="bar"></span>

</div>



            <!-- End: Google Style Text Input -->
            <h5 style="padding: 10px;">what does the expression 'Yikes' refer to ?</h5>
            <!-- Start: Google Style Text Input --><div class="form-group">

            <input type="text" name="q2" maxlength="100" required id="id_q2">
    <span class="highlight"></span>
    <span class="bar"></span>

</div>



            <!-- End: Google Style Text Input -->
            <h5 style="padding: 10px;">Here 'carnivore refers to whom'?</h5>
            <!-- Start: Google Style Text Input --><div class="form-group">

            <input type="text" name="q3" maxlength="100" required id="id_q3">
    <span class="highlight"></span>
    <span class="bar"></span>
</div>



            <!-- End: Google Style Text Input -->
            <h5 style="padding: 10px;">What do you mean by word 'tack'</h5>
            <!-- Start: Google Style Text Input --><div class="form-group">

            <input type="text" name="q4" maxlength="100" required id="id_q4">
    <span class="highlight"></span>
    <span class="bar"></span>
</div>



            <!-- End: Google Style Text Input -->
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        <!-- Start: Pretty Footer -->
        <footer>
            <div class="row">
                <div class="col-sm-6 col-md-4 footer-navigation">
                    <h3><a href="#">L i n g i s t o r&nbsp;</a></h3>
                    <p class="links"><a href="#">Home</a><strong> · </strong><a href="#">Blog</a><strong> · </strong><a href="#">Pricing</a><strong> · </strong><a href="#">About</a><strong> · </strong><a href="#">Faq</a><strong> · </strong><a href="#">Contact</a></p>
                    <p
                        class="company-name">Company Name © 2015 </p>
                </div>
                <div class="col-sm-6 col-md-4 footer-contacts">
                    <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                        <p><span class="new-line-span">Hitect City</span>Hyderabad, India</p>
                    </div>
                    <div><i class="fa fa-phone footer-contacts-icon"></i>
                        <p class="footer-center-info email text-left"> +91 6281277051</p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">support@company.com</a></p>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-4 footer-about">
                    <h4>About the company</h4>
                    <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                    <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
                </div>
            </div>
        </footer>
        <!-- End: Pretty Footer -->
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/script.min.js"></script>
</body>
</html>

django_project/ESL/templates/ESL/home.html
{% extends "ESL/base.html" %}
{% block content %}
<p></p>



{% endblock content%}